# Generated by Django 3.1.2 on 2020-10-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='silka',
            new_name='image',
        ),
    ]
