# Generated by Django 2.2.4 on 2020-10-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('planting_depth', models.PositiveIntegerField(default=0, help_text='cm')),
                ('flowers_color', models.CharField(max_length=128)),
                ('mature_height', models.PositiveIntegerField(default=0, help_text='cm')),
                ('bulb_size', models.PositiveIntegerField(default=0, help_text='cm')),
                ('bulb_spacing', models.PositiveIntegerField(default=0, help_text='cm')),
                ('description', models.TextField()),
                ('poison_toxic_for_animals', models.BooleanField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
